#!/usr/bin/env psql -h /tmp -v ON_ERROR_STOP=1 --username "rocky" --dbname "market" <<-EOSQL

export POSTGRES_DB=website
export POSTGRES_READ_USER=rocky
export POSTGRES_DB=website
export POSTGRES_READ_USER=rocky
export POSTGRES_CREATE_USER=rocky
export POSTGRES_UPDATE_USER=rocky
export POSTGRES_READ_USER_PASSWORD='changeMe'
export POSTGRES_CREATE_USER_PASSWORD='changeMe'
export POSTGRES_UPDATE_USER_PASSWORD='changeMe'
export POSTGRES_DELETE_USER_PASSWORD='changeMe'
export POSTGRES_CRUD_USER_PASSWORD='changeMe'



psql -h /tmp -U postgres  CREATE USER $POSTGRES_READ_USER WITH PASSWORD '$POSTGRES_READ_USER_PASSWORD';
psql -h /tmp -U postgres  CREATE USER $POSTGRES_CREATE_USER WITH PASSWORD '$POSTGRES_CREATE_USER_PASSWORD';
psql -h /tmp -U postgres  CREATE USER $POSTGRES_UPDATE_USER WITH PASSWORD '$POSTGRES_UPDATE_USER_PASSWORD';
psql -h /tmp -U postgres  CREATE USER $POSTGRES_DELETE_USER WITH PASSWORD '$POSTGRES_DELETE_USER_PASSWORD';
psql -h /tmp -U postgres  CREATE USER $POSTGRES_CRUD_USER WITH PASSWORD '$POSTGRES_CRUD_USER_PASSWORD';

psql -h /tmp -U postgres  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_READ_USER;
psql -h /tmp -U postgres  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_CREATE_USER;
psql -h /tmp -U postgres  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_UPDATE_USER;
psql -h /tmp -U postgres  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_DELETE_USER;
psql -h /tmp -U postgres  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_CRUD_USER;

psql -h /tmp -U postgres  GRANT USAGE ON SCHEMA public TO $POSTGRES_READ_USER;
psql -h /tmp -U postgres  GRANT USAGE ON SCHEMA public TO $POSTGRES_CREATE_USER;
psql -h /tmp -U postgres  GRANT USAGE ON SCHEMA public TO $POSTGRES_UPDATE_USER;
psql -h /tmp -U postgres  GRANT USAGE ON SCHEMA public TO $POSTGRES_DELETE_USER;
psql -h /tmp -U postgres  GRANT USAGE ON SCHEMA public TO $POSTGRES_CRUD_USER;

psql -h /tmp -U postgres  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRES_READ_USER;
psql -h /tmp -U postgres  GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO $POSTGRES_CREATE_USER;
psql -h /tmp -U postgres  GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA public TO $POSTGRES_UPDATE_USER;
psql -h /tmp -U postgres  GRANT SELECT, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_DELETE_USER;
psql -h /tmp -U postgres  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_CRUD_USER;

psql -h /tmp -U postgres  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_READ_USER;
psql -h /tmp -U postgres  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_CREATE_USER;
psql -h /tmp -U postgres  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_UPDATE_USER;
psql -h /tmp -U postgres  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_DELETE_USER;
psql -h /tmp -U postgres  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_CRUD_USER;

EOSQL
