server {
         listen       8686;
         server_name  thering.gc-pay.com;
         root         /var/www/html/public;

        error_log                   /proc/self/fd/2 debug;
        access_log                  /proc/self/fd/1 main;
         index index.html index.htm index.php;

         location / {
                      try_files $uri $uri/ /index.php$is_args$args;
         }

         location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/tmp/xx-pool.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
    }
}