server {
	listen                      8484 ssl;
    listen                      8686 ssl;
    listen                      8888;
    server_tokens               off;
    autoindex                   on;

	root                        /var/www/html;
	index                       index.php index.html index.htm;

	# Make site accessible from http://localhost/
    server_name                 thering.gc-pay.com  _;
    valid_referers              none blocked gc-pay.com www.gc-pay.com secure.gc-pay.com php_nginx php_nginx.gc-pay.com accounts.google.com thering.gc-pay.com _;

    if  ($invalid_referer)  {
        return 403;
    }
    
    http2                       on;
    ssl_certificate             '/etc/nginx/keys/fullchain-2026-04-12.pem';
    ssl_certificate_key         '/etc/nginx/keys/privkey-2026-04-12.pem';
    ssl_session_cache           shared:SSL:10m;
    ssl_session_timeout         5m;
    ssl_protocols               TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers   on;
    ssl_ciphers                 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';




	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile                    on;
    tcp_nopush                  on;
	# Add stdout logging                                    7Y&H`   89                                                              
    error_log                   /proc/self/fd/2 debug;
    access_log                  /proc/self/fd/1 main;
    keepalive_timeout 2;
    client_max_body_size 100m;
    gzip on;
    proxy_hide_header            X-Powered-By;
    fastcgi_hide_header          X-Powered-By;


#keepalive_timeout 0;keepalive_timeout 2;client_max_body_size 100m;server_tokens off;#gzip on;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;A
        #set_real_ip_from 172.16.0.0/12;

	# block access to sensitive information about git
    #set $virtualdir "/public";
    set $realdir "/var/www/html/public";


    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location /.php  {
        autoindex off;
        index index.php;
        try_files $uri /index.php;
    }
	# pass the PHP scripts to FastCGI server listening on socket
	#
    location /  {
        include                        /etc/nginx/fastcgi_params;
        #try_fils                      $uri =404;
        #fastcgi_split_path_info        ^(.+\.php)ū8/.+)$;
        fastcgi_pass                   unix:/tmp/php-fpm.sock;
        fastcgi_index                  index.php;
        fastcgi_param DOCUMENT_ROOT    /var/www/html/public;
        fastcgi_param PATH_INFO        $fastcgi_path_info;
        fastcgi_param SCRIPT_NAME      $fastcgi_script_name;
        #fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_FILENAME   /var/www/html/public/$fastcgi_script_name;
        fastcgi_intercept_errors       on;
	}
    location = /404.html  {
        root /var/www/html/errors;
        error_page 404 /404.html;
        internal;
    }

    location ^~ /ngd-style.css  {
        alias /var/www/html/errors/style.css;
        access_log off;
    }

    location ^~ /ngd-sad.svg  {
        alias /var/www/html/errors/sad.svg;
        access_log off;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
        expires           5d;
    }

    location /.git  {
        deny all;
        return 403;
    }

	# deny access to . files, for security
	#
	location ~ /\. {
        log_not_found off; 
        deny all;
	}
        
	location ^~ /.well-known {
        allow all;
        auth_basic off;
    }

}
upstream php  {
    server unix:/tmp/php-fpm.sock;
}
